image: "logstash"
imageTag: "7.5.0"
resources:
  requests:
    cpu: "400m"
    memory: "1536Mi"
  limits:
    cpu: "1000m"
    memory: "1536Mi"
volumeClaimTemplate:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 4Gi
nodeSelector:
  node-role: state

logstashConfig: {}
  logstash.yml: |
