elasticsearchURL: ""
elasticsearchHosts: "http://elasticsearch-master:9200"

image: "kibana"
imageTag: "7.3.2"

#files:
#  kibana.yml:
#    ## Default Kibana configuration from kibana-docker.
#    server.name: kibana
#    server.host: "0"
#    ## For kibana < 6.6, use elasticsearch.url instead
#    elasticsearch.hosts: http://elastic-elasticsearch-clie:9200
#
#    ## Custom config properties below
#    ## Ref: https://www.elastic.co/guide/en/kibana/current/settings.html
#    # server.port: 5601
#    # logging.verbose: "true"
#    # server.defaultRoute: "/app/kibana"
extraEnvs: 
  - name: "SERVER_BASEPATH"
    value: "/kibana"
  - name: "SERVER_REWRITEBASEPATH"
    value: "false"
readinessProbe:
  failureThreshold: 3
  initialDelaySeconds: 10
  periodSeconds: 10
  successThreshold: 3
  timeoutSeconds: 5
resources: 
   limits:
     cpu: 1000m
     memory: 600Mi
   requests:
     cpu: 1000m
     memory: 500Mi

