roles:
  master: "true"
  data: "true"
replicas: 1
minimumMasterNodes: 1
image: "elasticsearch"
imageTag: "7.3.2"
resources:
  requests:
    cpu: "1000m"
    memory: "2Gi"
  limits:
    cpu: "1100m"
    memory: "2Gi"
extraEnvs: 
  - name: action.auto_create_index
    value: "true"
    
volumeClaimTemplate:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 50Gi

nodeSelector:
  node-role: state

tests:
  enabled: false
