deploymentname: dev-ukassa-status
volumes:
  - name: config
    configMap:
      name: dev-ukassa-status
      defaultMode: 420
  - name: oracle
    configMap:
      name: tnsnames
      defaultMode: 420
image:
  repository: 10.1.10.86:5000
  tag: build4testing:s9184-api.ukassa.status-50-develop
  
ingress:
  enabled: true
  className: "nginx"
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: dev.testnew.egopay.ru
      paths:
        - path: /dev-ukassa-status
          pathType: Prefix
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
configmaptns:
  enabled: true
  data: 
    circus.conf: ''
    tnsnames.ora: |
      main =
         (DESCRIPTION =
           (ADDRESS = (PROTOCOL = TCP)(HOST = 10.1.10.199)(PORT = 1521))
           (CONNECT_DATA =
             (SERVICE_NAME = epaytest.egopay.ru)
           )
          )

      refund =
         (DESCRIPTION =
            (ADDRESS = (PROTOCOL = TCP)(HOST = vv-edudb-01.sirena-travel.ru)(PORT = 1521))
           (CONNECT_DATA =
            (SERVER = DEDICATED)
            (SERVICE_NAME = edu)
           )
         )
configmap:
  enabled: true
  data:
    appt.ini: |
      [main]
      mq_connect = amqp://admin:admin@10.1.100.189:9254
      data_connect = oracle://user=e_ukassa_status password=Ba5iejee2o service=main
      sets_connect = oracle://user=c_ukassa_status password=Ixah0ahGoh service=main
      logger = dest=udp addr=10.1.100.182:514 facility=0 filter=[+A] procnamefmt=N
  
      [ukassa]
      queue = TEST.UKASSA_STATUS
  
      [fiscalization_kz]
      queue = TEST.FISCALIZATION_KZ
  
    circus.conf: |
      [circus]
      [env]
      PYTHONPATH=/usr/local/lib/python3.9/site-packages
      LANG=ru_RU.UTF-8
      TNS_ADMIN=/oracle/
      LD_LIBRARY_PATH=/usr/lib/oracle/19.11/client/lib
      NLS_LANG=AMERICAN.UTF8
      [watcher:app]
      cmd = /usr/local/bin/pg_api_ukassa_status -c /config/appt.ini --fd $(circus.sockets.app)
      numprocesses = 1
      use_sockets = True
      stdout_stream.class = StdoutStream
      stderr_stream.class = StdoutStream
      [socket:app]
      host = 0.0.0.0
      port = 80

command:
  - /usr/local/bin/circusd
args:
  - /config/circus.conf
env:
  - name: TNS_ADMIN
    value: /oracle/
  - name: LD_LIBRARY_PATH
    value: /usr/lib/oracle/12.1/client/lib




volumeMounts:
  - name: oracle
    mountPath: /oracle
  - name: config
    mountPath: /config
strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%


resources:
  limits:
    cpu: 300m
    memory: 512Mi
  requests:
    cpu: 300m
    memory: 500Mi
