apiVersion: v1
kind: Service
metadata:
  name: riak
  namespace: egopay-stage
spec:
  ports:
    - name: http-pub
      protocol: TCP
      port: 8098
      targetPort: 8098
    - name: proto-buff-pub
      protocol: TCP
      port: 8087
      targetPort: 8087
    - name: ssh
      protocol: TCP
      port: 22
      targetPort: 22
  selector:
    app: s9931-riak
  type: ClusterIP
